#!/usr/bin/env bash
# Generates a minimal no-op stub of the private `otel-helper` package so tests
# can run WITHOUT access to the private repo (spec 36 T2).
#
# The stub mirrors the API surface src/ actually uses:
#   setup_telemetry() · get_tracer().start_as_current_span(...) · get_meter().create_*()
#   · metrics_app() (mounted at /metrics — otel-helper v0.2.0+)
#
# Usage: stub-otel.sh <target-dir>   → writes <target-dir>/otel_helper/__init__.py
set -euo pipefail

TARGET="${1:?usage: stub-otel.sh <target-dir>}"
mkdir -p "${TARGET}/otel_helper"

cat > "${TARGET}/otel_helper/__init__.py" <<'PY'
"""No-op stub of the private otel-helper package (generated by scripts/stub-otel.sh).

Local-test use ONLY. CI installs the real package via a deploy key — a run using
this stub does NOT validate telemetry wiring. See AGENTS.md ("passes locally
!= passes CI").
"""
from contextlib import contextmanager


class _Span:
    def set_attribute(self, *a, **kw): pass
    def set_attributes(self, *a, **kw): pass
    def record_exception(self, *a, **kw): pass
    def set_status(self, *a, **kw): pass
    def add_event(self, *a, **kw): pass


class _Tracer:
    @contextmanager
    def start_as_current_span(self, *a, **kw):
        yield _Span()

    def start_span(self, *a, **kw):
        return _Span()


class _Instrument:
    def add(self, *a, **kw): pass
    def record(self, *a, **kw): pass


class _Meter:
    def create_counter(self, *a, **kw): return _Instrument()
    def create_histogram(self, *a, **kw): return _Instrument()
    def create_up_down_counter(self, *a, **kw): return _Instrument()
    def create_gauge(self, *a, **kw): return _Instrument()
    def create_observable_gauge(self, *a, **kw): return _Instrument()


def setup_telemetry(*a, **kw):
    return None


def get_tracer(*a, **kw):
    return _Tracer()


def get_meter(*a, **kw):
    return _Meter()


class _StubMetricsApp:
    """Minimal ASGI app standing in for otel-helper's real Prometheus
    /metrics endpoint (v0.2.0+) — enough for `app.mount("/metrics", ...)`
    to succeed under test, not a real scrape target."""
    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            return
        await send({"type": "http.response.start", "status": 200, "headers": []})
        await send({"type": "http.response.body", "body": b""})


def metrics_app(*a, **kw):
    return _StubMetricsApp()
PY

echo "otel_helper stub written to ${TARGET}/otel_helper/"
